/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "error-container": "#93000a",
        "on-primary": "#5b1b00",
        "tertiary-container": "#349cbc",
        "secondary-fixed": "#e5e2db",
        "on-secondary-container": "#b7b5af",
        "surface-variant": "#353532",
        "on-surface-variant": "#ddc0b6",
        "primary-fixed": "#ffdbcf",
        "on-primary-fixed": "#380d00",
        "surface-container-low": "#1c1c1a",
        "on-tertiary-fixed-variant": "#004d61",
        "secondary-container": "#474742",
        "tertiary-fixed": "#b8eaff",
        "primary-container": "#e27042",
        "background": "#131312",
        "on-tertiary": "#003544",
        "on-tertiary-fixed": "#001f28",
        "inverse-primary": "#a14015",
        "outline": "#a58b82",
        "on-secondary-fixed-variant": "#474742",
        "secondary-fixed-dim": "#c9c6c0",
        "surface-dim": "#131312",
        "surface-tint": "#ffb59a",
        "surface-bright": "#3a3937",
        "primary-fixed-dim": "#ffb59a",
        "on-primary-container": "#4f1700",
        "inverse-on-surface": "#31302e",
        "tertiary-fixed-dim": "#74d3f4",
        "outline-variant": "#57423b",
        "surface": "#131312",
        "on-error-container": "#ffdad6",
        "secondary": "#c9c6c0",
        "surface-container-lowest": "#0e0e0c",
        "error": "#ffb4ab",
        "surface-container-high": "#2a2a28",
        "on-primary-fixed-variant": "#802a00",
        "primary": "#ffb59a",
        "on-background": "#e5e2de",
        "on-secondary-fixed": "#1c1c18",
        "tertiary": "#74d3f4",
        "on-error": "#690005",
        "surface-container": "#20201e",
        "inverse-surface": "#e5e2de",
        "on-secondary": "#31312c",
        "on-tertiary-container": "#002e3b",
        "surface-container-highest": "#353532"
      },
      borderRadius: {
        "DEFAULT": "0px",
        "none": "0px",
        "lg": "0px",
        "xl": "0px",
        "full": "9999px"
      },
      spacing: {
        "margin-page": "64px",
        "unit": "4px",
        "gutter": "24px",
        "margin-mobile": "20px",
        "max-width": "1200px"
      },
      fontFamily: {
        serif: ["Newsreader", "serif"],
        mono: ["JetBrains Mono", "monospace"],
        "headline-xl": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "headline-md": ["Newsreader", "serif"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
      },
      fontSize: {
        "headline-xl": ["64px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.4", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "1.6", fontWeight: "400" }],
        "label-sm": ["12px", { lineHeight: "1", letterSpacing: "0.05em", fontWeight: "500" }]
      }
    },
  },
  plugins: [],
};
